### ISSUE TITLE
Create Chatter bot

### ISSUE THREAD

**Issue by crcastle** [heroku/dreamhouse-disco-old#20]
- [x] Create Org62 user for Dreamhouse Disco
- [x] Background job to poll Dreamhouse Disco messages
- [x] Chatter client to communicate with Chatter API
- [x] ChatterMessage model to persist incoming messages
- [x] Queue SongRequest jobs to send new chatter messages to Disco
- [x] Post message thanking users for successful submissions
- [x] Post message with list of room names asking user to include name if they didn't

**Comment by thejonanshow** [comment]
These were created under the misguided assumption that we would be polling the API in Travolta to get new messages. Instead we created a dev org, added a Disco user, setup an Apex trigger to watch for Chatter feed items and used Heroku Connect to pull the new messages down directly to Dreamhouse Disco.
