### ISSUE TITLE
Fancy Facebook Replies

### ISSUE THREAD

**Issue by thejonanshow** [heroku/dreamhouse-disco-old#40]
Include the Album art in replies on Facebook.

**Comment by thejonanshow** [comment]
If the response from Disco includes an "image" attribute include it in the response on FB.

**Comment by crcastle** [comment]
@thejonanshow just watched the dev keynote preview.  emily demos a FB bot that has some cool interaction.  we don't need to make ours that awesome, but if you saw it I thought it might inspire other ideas for our FB integration.  Not sure if it was recorded, but can you ask Emily if there's an easy way for you to see it?
