### ISSUE TITLE
Song request response schema

### ISSUE THREAD

**Issue by thejonanshow** [heroku/dreamhouse-disco-old#41]
```
{
  "track" : "everything from Spotify",
  "recommended_playlist" : "optional link to CaseyKasum thank you page",
  "reply" : "optional override text for the response to the user"
}
```

**Comment by crcastle** [comment]
@thejonanshow just remembered that when dreamhouse disco receives the track request message from travolta, it responds before doing the spotify lookup.  So the reply can't include the spotify `track` Hash.  The spotify lookup happens in the worker later.... so... dreamhouse disco can return this:

``` json
{
  "recommended_playlist": "optional link to CaseyKasum thank you page",
  "reply": "optional override text for the response to the user"
}
```

i.e. no `track`

I'll noodle on some other ideas for things dreamhouse disco could return to you that would make your reply back to the user more exciting.

**Comment by thejonanshow** [comment]
OK you have an endpoint to create spotify tracks in Travolta.

When I first send you the song request I'll send you a song_request_id like this:

```
{
  "text" : "can't buy me love",
  "sender" : "123",
  "song_request_id" : "c9153a6f-97f0-4216-b94c-536d5a323616"
}
```

When you have the track data from Spotify POST this to /spotify_tracks:

```
{
  "song_request_id" : "<the_id_from_the_first_request", // required
  "track" : "<everything from spotify>", // optional
  "recommended_playlist" : "<link to CaseyKasem playlist" // optional
}
```

I'm expecting the track to look like this: https://developer.spotify.com/web-api/get-track/

Using that example I'm going to work on creating interesting replies in Facebook and Chatter tomorrow. If you know their example to be wrong or you're modifying the track JSON you should let me know.

If you don't send me a track I'll assume we didn't find anything and give them some feedback to that effect: "Sorry I couldn't find a song on Spotify using 'text you sent'! Don't give up, I have faith in you." (not implemented yet, depends on decision here: https://github.com/heroku/dreamhouse-disco/issues/29)

During these changes I moved all of the primary keys from integers to UUIDs for the Travolta models. If you have a Travolta in dev somewhere you'll need to drop the DB and rerun the migrations. Also if you're storing the IDs for DiscoRegistrations or anything else in disco the old ones are invalid. They should be recreated normally if you logout and log back in so you'll get the new ID.

**Comment by crcastle** [comment]
@thejonanshow 
- The JSON object I send you will be the spotify track schema you linked to above.
- Agree, if no "track" property is included in the JSON response, assume Dreamhouse could not find a song.
- Roger on the Travolta DB schema change.  I haven't deployed any Travoltas.  Should I force re-registration of staging and production (via logout and re-auth)?
