### ISSUE TITLE
Animate blue speaker icon when music is playing

### ISSUE THREAD

**Issue by crcastle** [heroku/dreamhouse-disco-old#50]
Add an indicator for whether music is playing or not.  Maybe animate the blue circle speaker icon in the top right of the now playing track with sound waves going out from the speaker?

I can handle swapping out the static vs animated version of this image to match play state.

**Comment by lynnandtonic** [comment]
See: https://github.com/heroku/dreamhouse-disco/issues/51#issuecomment-250325205

This should eliminate any need to swap out static vs. animated version of the image. HTML classes and CSS will show/hide the icon.
