### ISSUE TITLE
Provide play/pause/next buttons

### ISSUE THREAD

**Issue by crcastle** [heroku/dreamhouse-disco-old#51]
Happy for design suggestions here.  One idea I had was, on mouseover of the blue speaker image, extend the blue circle to the right so that it is a blue oval.  In that oval show a play or pause icon that is clickable to change play state beside a next track button to advance the track.

I can handle "wiring these up" -- i.e. the play/pause/next actions on click.  The animation, I could do or I think that one's doable with CSS.

**Comment by lynnandtonic** [comment]
For the Play/Pause/Next buttons: https://github.com/heroku/dreamhouse-disco/blob/ux-improvements/src/components/Music.js#L104-L105

I have it set up so adding a class of `playing` or `paused` to `<div className='track now-playing'>` will swap appropriate controls/styling.

When class is `playing` the animating blue icon will show and the Pause and Next buttons will show on hover of the cover art.

When class  is `paused` the animating blue icon will not show and the Play and Next buttons will show by default.

## 

I was also thinking we could swap the h2 text depending on the track's playing or paused status. See: https://github.com/heroku/dreamhouse-disco/blob/ux-improvements/src/components/Music.js#L100-L103

Think that's possible?
