### ISSUE TITLE
Add form call to action near the top of personalized page

### ISSUE THREAD

**Issue by lynnandtonic** [heroku/dreamhouse-disco-old#55]

**Comment by lynnandtonic** [comment]
@crcastle I set up the the cta button to link to the form for mobile. However because of the app's routing, I couldn't get it to link to an ID. Could you get it to link down to the form? It's here: https://github.com/heroku/dreamhouse-disco/blob/ux-improvements/src/components/Thanks.js#L44

**Comment by crcastle** [comment]
Hmm... I'm going to merge this in for now, but I've created a new issue #59 to get the button working.
